# Nixpacks configuration for Railway
# Instala Graphviz como dependencia del sistema

[phases.setup]
nixPkgs = ["...", "graphviz"]

[phases.install]
cmds = ["pip install -r requirements_api.txt"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
